# Constants

In [1]:
import tensorflow as tf

## Tensor

- Deeplearning framework는 기본적으로 Tensor를 다루는 도구다.
    - [Tensor](https://www.google.com/search?q=Tensor&newwindow=1&sxsrf=AOaemvLxCRvi46j5dRtWwY8K6ssvkpF48A:1641452781782&source=lnms&tbm=isch&sa=X&ved=2ahUKEwin2eSPyJz1AhXNdd4KHWzUAd8Q_AUoAXoECAIQAw&biw=1440&bih=820&dpr=2)


- Tensor를 다룰 때 가장 중요한 것! 

  ${\rightarrow} \ $ **SHAPE !!!**
  
 (해보면 알겠지만, 제일 에러 많이 나는 이유, 제일 헷갈리는 것, 개발할 때 우리가 이론을 알아야 하는 이유, 함수들의 설정값을 확인해야하는 이유)
 
 

## Tensor 생성

우리가 생성하는 것은 `tf.Tensor` 데이터!

**항상 체크 해야 할 것 !**
 - shape
 - dtype (데이터 타입이 같아야 연산이 가능합니다.)

<h4> Constant (상수)</h4>

- **```tf.constant()```**

    - list -> Tensor
    - tuple -> Tensor
    - Array -> Tensor

In [2]:
li_ten = tf.constant([1, 2, 3])
li_ten

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [3]:
li_ten_f = tf.constant([1., 2., 3.])
li_ten_f

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [4]:
tu_ten = tf.constant(((1, 2, 3), (1, 2, 3)), name="sample")
tu_ten

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [6]:
import numpy as np

arr = np.array([1., 2., 3.])#, dtype='float64')
arr_ten = tf.constant(arr)
arr_ten

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

#### 잠깐 옆으로 새서...
* double precision : 64bits
* single precision : 32bits
* half precision   : 16bits

### Numpy array 추출

In [7]:
arr_ten.numpy(), type(arr_ten.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [8]:
li_ten.numpy(), type(li_ten.numpy())

(array([1, 2, 3]), numpy.ndarray)

In [12]:
not_a_matrix = [[1,2,3], [4, 5], [6, 7, 8]]
# tf.constant(not_a_matrix)

- 구조가 안 맞는 리스트를 변환하면 에러가 발생한다.

### shpae, dtype 항상 체크!!

In [9]:
li_ten.shape, tu_ten.shape

(TensorShape([3]), TensorShape([2, 3]))

In [10]:
arr_ten.dtype, li_ten.dtype

(tf.float64, tf.int32)

In [15]:
# 1번 케이스
# tf.matmul(li_ten, tu_ten)

- [3]과 [2,3]의 내적은 불가

In [16]:
# 2번 케이스
# tf.matmul(tu_ten, li_ten)

- [2,3] [3]은 랭크(차원)이 안맞아서 내적이 불가

In [11]:
# 랭크 확인
print(li_ten.ndim)
print(tu_ten.ndim)

1
2


In [13]:
# 3번 케이스
# arr_ten * li_ten

- 데이터 타입이 달라서 계산 안 됨

### 데이터 타입 컨트롤하는 방법
  - `tf.cast`

In [14]:
# 미리 지정해주거나
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [15]:
# tf.cast를 사용. 다만, 많은 경우 미리 데이터타입을 정리해둘 수 있다.
tf.cast(tensor, dtype=tf.int16)

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 2, 3], dtype=int16)>

#### 간단 퀴즈 

아래 코드를 에러 없이 실행 하시오. 

In [16]:
arr_ten, li_ten

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>)

In [18]:
#arr_ten * li_ten

------

In [17]:
arr_ten * tf.cast(li_ten, tf.float64)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 4., 9.])>

### 특정 값의 Tensor 생성

 - `tf.ones`
 - `tf.zeros`
 - `tf.range`


In [19]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [20]:
tf.zeros((2, 5), dtype="int32")

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [21]:
tf.range(10)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [22]:
tf.range(1, 11)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

####  간단 퀴즈

**n 을 입력하면 첫항이 1이고 공비가 2인 등비수열을 생성하는 함수를 만드시오** 
(이 때 결과값은 tf.Tensor 데이터이고, 데이터 타입은 tf.int32)

$$
n = 10 \ 일 때 \\ \\
(1, 2, 4, 8, 16, 32, 64, 128, 256, 512)
$$

In [23]:
def geometric_sequence(n):
    pass

In [24]:
print(geometric_sequence(10))

None


-----

In [26]:
def geometric_sequence(n):
    r = tf.range(n, dtype='int32')
    s = tf.ones(n, dtype=tf.int32) * 2
    return s**r


In [27]:
print(geometric_sequence(10))

tf.Tensor([  1   2   4   8  16  32  64 128 256 512], shape=(10,), dtype=int32)


<h4> Random Value(난수)</h4>

- 무작위 값을 생성할 때 필요. 
- Noise를 재현 한다거나, test를 한다거나 할 때 많이 사용됨 
- 데이터 타입은 상수형태로 반환됨

**`tf.random`** 에 구현 되어 있음. 

  - `tf.random.normal`
      - Gaussian Normal Distribution
      
  - `tf.random.uniform`
      - Uniform Distribution
      
> 이렇게나 많습니다! [LINK](https://www.tensorflow.org/api_docs/python/tf/random)

In [28]:
## shape은 튜플형태로

shape = (3, 3)

In [29]:
tf.random.normal(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.21718334,  0.20530696, -2.4365132 ],
       [ 1.0459605 , -3.043937  ,  1.4225698 ],
       [-1.7026451 , -0.72068155, -0.6747387 ]], dtype=float32)>

In [31]:
tf.random.normal(shape, mean=100, stddev=10) # 평균이 100이며 표준편차가 10

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 93.35857 , 105.28501 ,  99.433304],
       [113.02376 , 100.72111 , 101.67053 ],
       [104.093124,  88.77731 ,  99.72013 ]], dtype=float32)>

- tf.random.uniform
    - TensorFlow에서 Uniform Distribution

In [32]:
tf.random.uniform(shape)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.949988  , 0.7504935 , 0.11128616],
       [0.28930676, 0.8184172 , 0.00565732],
       [0.7169044 , 0.30540693, 0.6533543 ]], dtype=float32)>

* **Random seed 관리 하기!!!**

 - Random value로 보통 가중치를 초기화 
 - 이외에도 학습과정에서 Random value가 많이 사용됨. 
 - 이를 관리 안해주면, 자신이 했던 작업이 동일하게 복구 또는 재현이 안됨!!! 
 
 
- **`tf.random.set_seed({seed_number})`**

 
**=> 항상 Random seed를 고정해두고 개발 한다!!!** 
   
   (주의 할 점은 해당 개발물에 사용되는 난수가 모두 TensorFlow에서 생성된것이 아닐 수 있다는 것이다.) 

In [33]:
seed = 7777

In [34]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


In [36]:
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.7821541], shape=(1,), dtype=float32)
tf.Tensor([0.49664533], shape=(1,), dtype=float32)


In [37]:
tf.random.set_seed(seed)
a = tf.random.uniform([1])
b = tf.random.uniform([1])
print(a, b, sep="\n")

tf.Tensor([0.959749], shape=(1,), dtype=float32)
tf.Tensor([0.8677443], shape=(1,), dtype=float32)


- 랜덤 seed를 넣어주면 랜덤값 고정