# Tensor 연산

In [1]:
import tensorflow as tf
import numpy as np

아래의 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용하는게 가능!

* `tf.add`: 덧셈       : +
* `tf.subtract`: 뺄셈 : -
* `tf.multiply`: 곱셈 : *
* `tf.divide`: 나눗셈 : /
* `tf.pow`: n-제곱 : **
* `tf.negative`: 음수 부호 : -


In [2]:
a = tf.range(6, dtype=tf.int32)    # 0,1,2,3,4,5
b = 2 * tf.ones(6, dtype=tf.int32) # 2,2,2,2,2,2

tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

In [3]:
a + b    # == tf.add(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 3, 4, 5, 6, 7])>

**여러가지 연산**

* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [4]:
tf.maximum(a, b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([2, 2, 2, 3, 4, 5])>

#### Axis 이해하기

In [5]:
rank_2 = tf.random.normal((3, 3))

In [6]:
rank_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.39814213,  1.769758  ,  2.1790667 ],
       [ 0.7286186 ,  1.0718534 ,  0.5475342 ],
       [-0.07769339, -1.0954499 , -1.126094  ]], dtype=float32)>

In [7]:
rank_2[0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.39814213, 1.769758  , 2.1790667 ], dtype=float32)>

In [8]:
rank_2[0, 0]

<tf.Tensor: shape=(), dtype=float32, numpy=0.39814213>

### 3차원

In [9]:
rank_3 = tf.random.normal((3, 3, 3))

In [10]:
rank_3

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.115948  ,  0.23084545,  0.13986737],
        [ 0.18146299, -1.9267255 ,  1.2633066 ],
        [ 1.2865529 , -0.25478554, -1.6716673 ]],

       [[-1.3088338 ,  0.6820537 ,  0.37961668],
        [ 1.0021443 ,  1.1020442 ,  2.3583856 ],
        [-1.0938799 ,  2.1537602 , -0.7997435 ]],

       [[ 1.0792235 , -0.14832015,  0.51082844],
        [-0.36452863, -1.087566  , -0.02816686],
        [-1.2336739 ,  0.4822116 ,  1.2707691 ]]], dtype=float32)>

In [11]:
rank_3[1,1,2]

<tf.Tensor: shape=(), dtype=float32, numpy=2.3583856>

### 4차원...

In [12]:
rank_4 = tf.random.normal((3, 3, 3, 3))

In [13]:
rank_4

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[-0.22613189,  0.28266644,  0.2827372 ],
         [ 0.8900553 ,  1.9183443 ,  0.88590634],
         [ 0.32991943, -0.57631737, -0.31636676]],

        [[-0.24353571,  0.43533817,  0.21266663],
         [-1.9830531 , -0.27059138, -0.43016696],
         [-0.54962003, -1.154779  , -0.6834425 ]],

        [[ 0.5097373 , -1.6783874 ,  0.8509665 ],
         [-1.4350357 , -0.08479296, -0.80452055],
         [-0.9322655 ,  0.38514045,  0.06703473]]],


       [[[-1.2863257 , -1.3312482 , -1.396127  ],
         [-0.8945677 ,  1.6948917 ,  1.0584102 ],
         [-0.53903884,  0.98152065,  0.33956978]],

        [[-0.48450866, -1.0257032 ,  0.3016834 ],
         [ 0.7684464 , -1.0286465 , -0.28119454],
         [ 0.7495225 ,  1.267065  ,  0.07127785]],

        [[ 2.3458343 , -0.09044173,  0.40525675],
         [-0.56357294,  0.6821229 ,  0.20027688],
         [-0.23397176, -0.860456  ,  0.396742  ]]],


       [[[-0.29762584, -1.6409

In [14]:
rank_4[1,2,1,0]

<tf.Tensor: shape=(), dtype=float32, numpy=-0.56357294>

**차원 축소 연산**

* `tf.reduce_mean`: 설정한 축의 평균을 구한다. 
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다. 
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다. 
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다. 
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다. 

In [15]:
a

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5])>

In [16]:
tf.reduce_sum(a, axis=0), # 1 + 2 + 3 + 4 + 5, 차원 0 => 스칼라값

(<tf.Tensor: shape=(), dtype=int32, numpy=15>,)

In [17]:
tf.reduce_sum(a, axis=0, keepdims=True) # 차원 유지

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([15])>

In [21]:
b = tf.random.normal((2, 7))
b

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[ 0.31923726,  0.66946393, -0.62615275,  0.8556561 , -0.39368197,
         0.4237755 , -0.64446926],
       [-0.0089515 ,  0.72027147, -0.09445363, -0.60379034,  0.14183673,
        -0.24926859,  0.50220466]], dtype=float32)>

In [22]:
tf.reduce_mean(b, axis=1) # --> 평균 : 결과 2개값

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.08626126, 0.05826411], dtype=float32)>

In [23]:
tf.reduce_mean(b, axis=0) # ↓ 평균 : 결과 7개 값

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([ 0.15514289,  0.69486773, -0.3603032 ,  0.12593287, -0.12592262,
        0.08725345, -0.0711323 ], dtype=float32)>

In [24]:
c = tf.random.normal((2, 4, 3))
c

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[-0.591768  ,  0.10008945,  0.45401996],
        [-0.6142918 ,  1.5059266 ,  0.13828094],
        [-1.9324801 ,  0.2968577 ,  0.2449193 ],
        [-2.758796  ,  2.0170872 , -0.37225488]],

       [[ 0.9936794 , -1.3130609 , -0.57739097],
        [ 0.09752806,  0.75278795,  1.6381575 ],
        [ 0.2709007 , -1.7017047 ,  0.08738305],
        [-1.6442024 , -0.10869202, -0.8578436 ]]], dtype=float32)>

In [25]:
tf.reduce_mean(c, axis=0)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.20095569, -0.6064857 , -0.0616855 ],
       [-0.25838187,  1.1293573 ,  0.88821924],
       [-0.8307897 , -0.7024235 ,  0.16615117],
       [-2.2014992 ,  0.9541976 , -0.61504924]], dtype=float32)>

In [26]:
tf.reduce_mean(c, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.474334  ,  0.97999024,  0.11624133],
       [-0.07052353, -0.5926674 ,  0.07257648]], dtype=float32)>

In [27]:
tf.reduce_mean(c, axis=2)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.01255288,  0.34330526, -0.4635677 , -0.3713212 ],
       [-0.29892415,  0.82949114, -0.44780698, -0.870246  ]],
      dtype=float32)>

행렬과 관련된 연산

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [28]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [1., 1.]], dtype=float32)>

In [29]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)>

**크기 및 차원을 바꾸는 명령**
 (잘 사용됩니다!!)
 
이를 사용 할 때는 축을 잘 이해하고 사용하시면 좋습니다. 

* `tf.reshape`: 벡터 행렬의 크기 변환
* `tf.transpose`: 전치 연산
* `tf.expand_dims`: 지정한 축으로 차원을 추가
* `tf.squeeze`: 벡터로 차원을 축소

In [30]:
a = tf.range(6, dtype=tf.int32)      # [0, 1, 2, 3, 4, 5]

print("a     :", a, "\n")

a_2d = tf.reshape(a, (2, 3))  # 1차원 벡터는 2x3 크기의 2차원 행렬로 변환

print("a_2d  :", a_2d, "\n")

a_2d_t = tf.transpose(a_2d)   # 2x3 크기의 2차원 행렬을 3x2 크기의 2차원 행렬로 변환

print("a_2d_t:", a_2d_t, "\n")

## expand_dims에서 숫자는 차원을 늘릴 위치
a_3d = tf.expand_dims(a_2d, 0) # 2x3 크기의 2차원 행렬을 1x2x3 크기의 3차원 행렬로 변환
print("a_3d  :", a_3d, "\n")
a_4d = tf.expand_dims(a_3d, 3) # 1x2x3 크기의 3차원 행렬을 1x2x3x1 크기의 4차원 행렬로 변환
## 여기서 3을 -1로 해도됨

print("a_4d  :", a_4d, "\n")

a_1d = tf.squeeze(a_4d) # 원소의 개수가 1인 차원은 버린다, axis를 기준으로 넣을수있다.

print("a_1d  :", a_1d, "\n")   # 1x2x3x1 크기의 4차원 행렬을 2차원 벡터로 변환
                               # 1x2x3x1  ==> 2x3

a     : tf.Tensor([0 1 2 3 4 5], shape=(6,), dtype=int32) 

a_2d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 

a_2d_t: tf.Tensor(
[[0 3]
 [1 4]
 [2 5]], shape=(3, 2), dtype=int32) 

a_3d  : tf.Tensor(
[[[0 1 2]
  [3 4 5]]], shape=(1, 2, 3), dtype=int32) 

a_4d  : tf.Tensor(
[[[[0]
   [1]
   [2]]

  [[3]
   [4]
   [5]]]], shape=(1, 2, 3, 1), dtype=int32) 

a_1d  : tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32) 



**텐서를 나누거나 두 개 이상의 텐서를 합치는 명령**

* `tf.slice`: 특정 부분을 추출
* `tf.split`: 분할
* `tf.concat`: 합치기
* `tf.tile`: 복제-붙이기
* `tf.stack`: 합성
* `tf.unstack`: 분리 

In [31]:
a = tf.reshape(tf.range(12), (3, 4))
a

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [32]:
tf.slice(a, [0, 1], [2, 3])   # (0, 1)위치에서 (2개, 3개)만큼 뽑아낸다.

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]])>

In [33]:
a1, a2 = tf.split(a, num_or_size_splits=2, axis=1)  # 가로축(axis=1)을 따라 2개로 분할 
print(a1)
print(a2)

tf.Tensor(
[[0 1]
 [4 5]
 [8 9]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [34]:
tf.concat([a1, a2], 1) # 가로축(axis=1)을 따라 a1, a2를 합치기

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [37]:
a1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [4, 5],
       [8, 9]])>

In [38]:
tf.tile(a1, [1, 3])  # 가로축(axis=1)을 따라 3개로 복사-붙이기

<tf.Tensor: shape=(3, 6), dtype=int32, numpy=
array([[0, 1, 0, 1, 0, 1],
       [4, 5, 4, 5, 4, 5],
       [8, 9, 8, 9, 8, 9]])>

In [39]:
a3 = tf.stack([a1, a2])  # 3x2 행렬 a1, a2를 추가적인 차원으로 붙여서 2x3x2 고차원 텐서 생성
a3

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])>

In [40]:
tf.unstack(a3, axis=1)  # 2x3x2 고차원 텐서를 0차원으로 풀어서 3개의 2x2 행렬 생성

[<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[0, 1],
        [2, 3]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 8,  9],
        [10, 11]])>]

#### 간단 퀴즈

다음 코드를 에러 없이 실행하라. 

In [48]:
a = tf.constant(((1, 2, 3), (1, 2, 3)))
b = tf.constant([1, 2, 3])

#tf.matmul(a, b)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [54]:
b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

-----

#### b를 2차원으로 늘리자!

In [59]:
tf.expand_dims(b, axis=1)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3]])>

In [58]:
tf.matmul(a, tf.expand_dims(b, axis=1))

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[14],
       [14]])>